name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  python:
    name: Run Python tests
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: 1.5.1
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Update Poetry and dependencies
      working-directory: ./packages/python/laila-api
      run: |
        poetry self update
        poetry update

    - name: Install project dependencies
      working-directory: ./packages/python/laila-api
      run: poetry install --no-interaction
      

    - name: Run tests
      working-directory: ./packages/python/laila-api
      run: |
        poetry run pytest